// <auto-generated />
using System;
using DbModel;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Polleria.Migrations
{
    [DbContext(typeof(PolleriaDbContext))]
    [Migration("20260412191532_final")]
    partial class final
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DbModel.Tables.Banner", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LinkUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<string>("Subtitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Banners");
                });

            modelBuilder.Entity("DbModel.Tables.Cargo", b =>
                {
                    b.Property<int>("IdCargo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_cargo");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCargo"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("descripcion");

                    b.Property<bool>("EstadoLogico")
                        .HasColumnType("bit")
                        .HasColumnName("estado_logico");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("nombre");

                    b.HasKey("IdCargo");

                    b.ToTable("cargo");
                });

            modelBuilder.Entity("DbModel.Tables.CategoriaProducto", b =>
                {
                    b.Property<int>("IdCategoria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_categoria");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCategoria"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("descripcion");

                    b.Property<bool>("EstadoLogico")
                        .HasColumnType("bit")
                        .HasColumnName("estado_logico");

                    b.Property<string>("Nombre")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("nombre");

                    b.HasKey("IdCategoria");

                    b.ToTable("categoria_producto");
                });

            modelBuilder.Entity("DbModel.Tables.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("DbModel.Tables.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("DbModel.Tables.Cliente", b =>
                {
                    b.Property<int>("IdCliente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_cliente");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCliente"));

                    b.Property<string>("Apellidos")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("apellidos");

                    b.Property<bool>("EstadoLogico")
                        .HasColumnType("bit")
                        .HasColumnName("estado_logico");

                    b.Property<int?>("IdDireccion")
                        .HasColumnType("int")
                        .HasColumnName("id_direccion");

                    b.Property<int?>("IdTipoDocumento")
                        .HasColumnType("int")
                        .HasColumnName("id_tipodocumento");

                    b.Property<string>("Nombre")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("nombre");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("telefono");

                    b.HasKey("IdCliente");

                    b.HasIndex("IdTipoDocumento");

                    b.ToTable("cliente");
                });

            modelBuilder.Entity("DbModel.Tables.DetallePedido", b =>
                {
                    b.Property<int>("IdDetalle")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_detalle");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDetalle"));

                    b.Property<int?>("Cantidad")
                        .HasColumnType("int")
                        .HasColumnName("cantidad");

                    b.Property<int?>("IdPedido")
                        .HasColumnType("int")
                        .HasColumnName("id_pedido");

                    b.Property<int?>("IdProducto")
                        .HasColumnType("int")
                        .HasColumnName("id_producto");

                    b.Property<decimal?>("Subtotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("subtotal");

                    b.HasKey("IdDetalle");

                    b.HasIndex("IdPedido");

                    b.HasIndex("IdProducto");

                    b.ToTable("detalle_pedido");
                });

            modelBuilder.Entity("DbModel.Tables.Direccion", b =>
                {
                    b.Property<int>("IdDireccion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_direccion");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDireccion"));

                    b.Property<int?>("IdCliente")
                        .HasColumnType("int")
                        .HasColumnName("id_cliente");

                    b.Property<int?>("IdPedido")
                        .HasColumnType("int")
                        .HasColumnName("id_pedido");

                    b.HasKey("IdDireccion");

                    b.HasIndex("IdCliente")
                        .IsUnique()
                        .HasFilter("[id_cliente] IS NOT NULL");

                    b.HasIndex("IdPedido");

                    b.ToTable("direccion");
                });

            modelBuilder.Entity("DbModel.Tables.Empleado", b =>
                {
                    b.Property<int>("IdEmpleado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_empleado");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEmpleado"));

                    b.Property<string>("Contrasena")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("contrasena");

                    b.Property<bool>("EstadoLogico")
                        .HasColumnType("bit")
                        .HasColumnName("estado_logico");

                    b.Property<DateTime?>("FechaCreacion")
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha_creacion");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha_modificacion");

                    b.Property<int?>("IdCargo")
                        .HasColumnType("int")
                        .HasColumnName("id_cargo");

                    b.Property<int?>("IdTipoDocumento")
                        .HasColumnType("int")
                        .HasColumnName("id_tipodocumento");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("nombre");

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("nombre_usuario");

                    b.Property<string>("NumeroDocumento")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("numero_documento");

                    b.HasKey("IdEmpleado");

                    b.HasIndex("IdCargo");

                    b.HasIndex("IdTipoDocumento");

                    b.ToTable("empleado");
                });

            modelBuilder.Entity("DbModel.Tables.EstadoPedido", b =>
                {
                    b.Property<int>("IdEstado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_estado");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEstado"));

                    b.Property<string>("Nombre")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("nombre");

                    b.HasKey("IdEstado");

                    b.ToTable("estado_pedido");
                });

            modelBuilder.Entity("DbModel.Tables.EstadoRuta", b =>
                {
                    b.Property<int>("IdEstadoRuta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_estado_ruta");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEstadoRuta"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("descripcion");

                    b.Property<int?>("IdHistorial")
                        .HasColumnType("int")
                        .HasColumnName("id_historial");

                    b.Property<decimal?>("Latitud")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(10,8)")
                        .HasColumnName("latitud");

                    b.Property<decimal?>("Longitud")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(11,8)")
                        .HasColumnName("longitud");

                    b.Property<string>("UbicacionActual")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("ubicacion_actual");

                    b.HasKey("IdEstadoRuta");

                    b.HasIndex("IdHistorial");

                    b.ToTable("estado_ruta");
                });

            modelBuilder.Entity("DbModel.Tables.HistorialEstadoPedido", b =>
                {
                    b.Property<int>("IdHistorial")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_historial");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdHistorial"));

                    b.Property<DateTime?>("FechaFin")
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha_fin");

                    b.Property<DateTime?>("FechaInicio")
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha_inicio");

                    b.Property<int?>("IdEstado")
                        .HasColumnType("int")
                        .HasColumnName("id_estado");

                    b.Property<int?>("IdPedido")
                        .HasColumnType("int")
                        .HasColumnName("id_pedido");

                    b.HasKey("IdHistorial");

                    b.HasIndex("IdEstado");

                    b.HasIndex("IdPedido");

                    b.ToTable("historial_estado_pedido");
                });

            modelBuilder.Entity("DbModel.Tables.Invoice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CdrUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<string>("PdfUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Serie")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("XmlUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Invoices");
                });

            modelBuilder.Entity("DbModel.Tables.MetodoPago", b =>
                {
                    b.Property<int>("IdMetodo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_metodo");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdMetodo"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("descripcion");

                    b.Property<bool>("EstadoLogico")
                        .HasColumnType("bit")
                        .HasColumnName("estado_logico");

                    b.Property<string>("Nombre")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("nombre");

                    b.HasKey("IdMetodo");

                    b.ToTable("metodo_pago");
                });

            modelBuilder.Entity("DbModel.Tables.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ClientId")
                        .HasColumnType("int");

                    b.Property<int?>("DeliveryUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("DbModel.Tables.OrderDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int?>("SideId")
                        .HasColumnType("int");

                    b.Property<decimal>("Subtotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("SideId");

                    b.ToTable("OrderDetails");
                });

            modelBuilder.Entity("DbModel.Tables.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<string>("PaymentMethod")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TransactionId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("DbModel.Tables.Pedido", b =>
                {
                    b.Property<int>("IdPedido")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_pedido");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPedido"));

                    b.Property<DateTime?>("Fecha")
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha");

                    b.Property<DateTime?>("FechaPago")
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha_pago");

                    b.Property<int?>("IdCliente")
                        .HasColumnType("int")
                        .HasColumnName("id_cliente");

                    b.Property<int?>("IdComprobante")
                        .HasColumnType("int")
                        .HasColumnName("id_comprobante");

                    b.Property<int?>("IdEmpleado")
                        .HasColumnType("int")
                        .HasColumnName("id_empleado");

                    b.Property<int?>("IdEstadoActual")
                        .HasColumnType("int")
                        .HasColumnName("id_estado_actual");

                    b.Property<int?>("IdMetodo")
                        .HasColumnType("int")
                        .HasColumnName("id_metodo");

                    b.Property<int?>("IdRepartidor")
                        .HasColumnType("int")
                        .HasColumnName("id_repartidor");

                    b.Property<decimal?>("MontoPagado")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("monto_pagado");

                    b.Property<string>("Notas")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("notas");

                    b.HasKey("IdPedido");

                    b.HasIndex("IdCliente");

                    b.HasIndex("IdComprobante");

                    b.HasIndex("IdEmpleado");

                    b.HasIndex("IdEstadoActual");

                    b.HasIndex("IdMetodo");

                    b.HasIndex("IdRepartidor");

                    b.ToTable("pedido");
                });

            modelBuilder.Entity("DbModel.Tables.PedidoEmpleado", b =>
                {
                    b.Property<int>("IdPedido")
                        .HasColumnType("int")
                        .HasColumnName("id_pedido");

                    b.Property<int>("IdEmpleado")
                        .HasColumnType("int")
                        .HasColumnName("id_empleado");

                    b.Property<string>("Rol")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("rol");

                    b.HasKey("IdPedido", "IdEmpleado");

                    b.HasIndex("IdEmpleado");

                    b.ToTable("pedido_empleado");
                });

            modelBuilder.Entity("DbModel.Tables.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("BasePrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal?>("SalePrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("DbModel.Tables.Producto", b =>
                {
                    b.Property<int>("IdProducto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_producto");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdProducto"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("descripcion");

                    b.Property<bool>("EstadoLogico")
                        .HasColumnType("bit")
                        .HasColumnName("estado_logico");

                    b.Property<int?>("IdCategoria")
                        .HasColumnType("int")
                        .HasColumnName("id_categoria");

                    b.Property<string>("Nombre")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("nombre");

                    b.Property<decimal>("Precio")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("precio");

                    b.HasKey("IdProducto");

                    b.HasIndex("IdCategoria");

                    b.ToTable("producto");
                });

            modelBuilder.Entity("DbModel.Tables.Puesto", b =>
                {
                    b.Property<int>("IdPuesto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_puesto");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPuesto"));

                    b.Property<bool>("Estado")
                        .HasColumnType("bit")
                        .HasColumnName("estado");

                    b.Property<string>("Rol")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("rol");

                    b.HasKey("IdPuesto");

                    b.ToTable("puesto");
                });

            modelBuilder.Entity("DbModel.Tables.PuestoEmpleado", b =>
                {
                    b.Property<int>("IdPuesto")
                        .HasColumnType("int")
                        .HasColumnName("id_puesto");

                    b.Property<int>("IdEmpleado")
                        .HasColumnType("int")
                        .HasColumnName("id_empleado");

                    b.Property<DateTime?>("FechaFin")
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha_fin");

                    b.Property<DateTime?>("FechaInicio")
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha_inicio");

                    b.HasKey("IdPuesto", "IdEmpleado");

                    b.HasIndex("IdEmpleado");

                    b.ToTable("puesto_empleado");
                });

            modelBuilder.Entity("DbModel.Tables.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("DbModel.Tables.Side", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Sides");
                });

            modelBuilder.Entity("DbModel.Tables.TipoComprobante", b =>
                {
                    b.Property<int>("IdComprobante")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_comprobante");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdComprobante"));

                    b.Property<bool>("EstadoLogico")
                        .HasColumnType("bit")
                        .HasColumnName("estado_logico");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("tipo");

                    b.HasKey("IdComprobante");

                    b.ToTable("tipo_comprobante");
                });

            modelBuilder.Entity("DbModel.Tables.TipoDocumento", b =>
                {
                    b.Property<int>("IdTipoDocumento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_tipodocumento");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTipoDocumento"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("descripcion");

                    b.HasKey("IdTipoDocumento");

                    b.ToTable("tipodocumento");
                });

            modelBuilder.Entity("DbModel.Tables.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("DbModel.Tables.Cliente", b =>
                {
                    b.HasOne("DbModel.Tables.TipoDocumento", "TipoDocumento")
                        .WithMany("Clientes")
                        .HasForeignKey("IdTipoDocumento");

                    b.Navigation("TipoDocumento");
                });

            modelBuilder.Entity("DbModel.Tables.DetallePedido", b =>
                {
                    b.HasOne("DbModel.Tables.Pedido", "Pedido")
                        .WithMany("Detalles")
                        .HasForeignKey("IdPedido")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("DbModel.Tables.Producto", "Producto")
                        .WithMany("Detalles")
                        .HasForeignKey("IdProducto")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Pedido");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("DbModel.Tables.Direccion", b =>
                {
                    b.HasOne("DbModel.Tables.Cliente", "Cliente")
                        .WithOne("Direccion")
                        .HasForeignKey("DbModel.Tables.Direccion", "IdCliente")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DbModel.Tables.Pedido", "Pedido")
                        .WithMany("Direcciones")
                        .HasForeignKey("IdPedido")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Cliente");

                    b.Navigation("Pedido");
                });

            modelBuilder.Entity("DbModel.Tables.Empleado", b =>
                {
                    b.HasOne("DbModel.Tables.Cargo", "Cargo")
                        .WithMany("Empleados")
                        .HasForeignKey("IdCargo");

                    b.HasOne("DbModel.Tables.TipoDocumento", "TipoDocumento")
                        .WithMany("Empleados")
                        .HasForeignKey("IdTipoDocumento");

                    b.Navigation("Cargo");

                    b.Navigation("TipoDocumento");
                });

            modelBuilder.Entity("DbModel.Tables.EstadoRuta", b =>
                {
                    b.HasOne("DbModel.Tables.HistorialEstadoPedido", "Historial")
                        .WithMany("EstadosRuta")
                        .HasForeignKey("IdHistorial")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Historial");
                });

            modelBuilder.Entity("DbModel.Tables.HistorialEstadoPedido", b =>
                {
                    b.HasOne("DbModel.Tables.EstadoPedido", "Estado")
                        .WithMany("Historiales")
                        .HasForeignKey("IdEstado")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DbModel.Tables.Pedido", "Pedido")
                        .WithMany("Historiales")
                        .HasForeignKey("IdPedido")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Estado");

                    b.Navigation("Pedido");
                });

            modelBuilder.Entity("DbModel.Tables.OrderDetail", b =>
                {
                    b.HasOne("DbModel.Tables.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DbModel.Tables.Side", "Side")
                        .WithMany()
                        .HasForeignKey("SideId");

                    b.Navigation("Product");

                    b.Navigation("Side");
                });

            modelBuilder.Entity("DbModel.Tables.Pedido", b =>
                {
                    b.HasOne("DbModel.Tables.Cliente", "Cliente")
                        .WithMany("Pedidos")
                        .HasForeignKey("IdCliente")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DbModel.Tables.TipoComprobante", "TipoComprobante")
                        .WithMany("Pedidos")
                        .HasForeignKey("IdComprobante")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DbModel.Tables.Empleado", "Empleado")
                        .WithMany("PedidosGestionados")
                        .HasForeignKey("IdEmpleado")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DbModel.Tables.EstadoPedido", "EstadoActual")
                        .WithMany("Pedidos")
                        .HasForeignKey("IdEstadoActual")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DbModel.Tables.MetodoPago", "MetodoPago")
                        .WithMany("Pedidos")
                        .HasForeignKey("IdMetodo")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DbModel.Tables.Empleado", "Repartidor")
                        .WithMany("PedidosRepartidos")
                        .HasForeignKey("IdRepartidor")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Cliente");

                    b.Navigation("Empleado");

                    b.Navigation("EstadoActual");

                    b.Navigation("MetodoPago");

                    b.Navigation("Repartidor");

                    b.Navigation("TipoComprobante");
                });

            modelBuilder.Entity("DbModel.Tables.PedidoEmpleado", b =>
                {
                    b.HasOne("DbModel.Tables.Empleado", "Empleado")
                        .WithMany("PedidosEmpleados")
                        .HasForeignKey("IdEmpleado")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DbModel.Tables.Pedido", "Pedido")
                        .WithMany("PedidosEmpleados")
                        .HasForeignKey("IdPedido")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empleado");

                    b.Navigation("Pedido");
                });

            modelBuilder.Entity("DbModel.Tables.Product", b =>
                {
                    b.HasOne("DbModel.Tables.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("DbModel.Tables.Producto", b =>
                {
                    b.HasOne("DbModel.Tables.CategoriaProducto", "Categoria")
                        .WithMany("Productos")
                        .HasForeignKey("IdCategoria");

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("DbModel.Tables.PuestoEmpleado", b =>
                {
                    b.HasOne("DbModel.Tables.Empleado", "Empleado")
                        .WithMany("PuestosEmpleados")
                        .HasForeignKey("IdEmpleado")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DbModel.Tables.Puesto", "Puesto")
                        .WithMany("PuestosEmpleados")
                        .HasForeignKey("IdPuesto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empleado");

                    b.Navigation("Puesto");
                });

            modelBuilder.Entity("DbModel.Tables.Cargo", b =>
                {
                    b.Navigation("Empleados");
                });

            modelBuilder.Entity("DbModel.Tables.CategoriaProducto", b =>
                {
                    b.Navigation("Productos");
                });

            modelBuilder.Entity("DbModel.Tables.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("DbModel.Tables.Cliente", b =>
                {
                    b.Navigation("Direccion");

                    b.Navigation("Pedidos");
                });

            modelBuilder.Entity("DbModel.Tables.Empleado", b =>
                {
                    b.Navigation("PedidosEmpleados");

                    b.Navigation("PedidosGestionados");

                    b.Navigation("PedidosRepartidos");

                    b.Navigation("PuestosEmpleados");
                });

            modelBuilder.Entity("DbModel.Tables.EstadoPedido", b =>
                {
                    b.Navigation("Historiales");

                    b.Navigation("Pedidos");
                });

            modelBuilder.Entity("DbModel.Tables.HistorialEstadoPedido", b =>
                {
                    b.Navigation("EstadosRuta");
                });

            modelBuilder.Entity("DbModel.Tables.MetodoPago", b =>
                {
                    b.Navigation("Pedidos");
                });

            modelBuilder.Entity("DbModel.Tables.Pedido", b =>
                {
                    b.Navigation("Detalles");

                    b.Navigation("Direcciones");

                    b.Navigation("Historiales");

                    b.Navigation("PedidosEmpleados");
                });

            modelBuilder.Entity("DbModel.Tables.Producto", b =>
                {
                    b.Navigation("Detalles");
                });

            modelBuilder.Entity("DbModel.Tables.Puesto", b =>
                {
                    b.Navigation("PuestosEmpleados");
                });

            modelBuilder.Entity("DbModel.Tables.TipoComprobante", b =>
                {
                    b.Navigation("Pedidos");
                });

            modelBuilder.Entity("DbModel.Tables.TipoDocumento", b =>
                {
                    b.Navigation("Clientes");

                    b.Navigation("Empleados");
                });
#pragma warning restore 612, 618
        }
    }
}
