// <auto-generated />
using System;
using DbModel;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Polleria.Migrations
{
    [DbContext(typeof(PolleriaDbContext))]
    [Migration("20260416015646_CrearStoredProcedureReportes")]
    partial class CrearStoredProcedureReportes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DbModel.Tables.Banner", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LinkUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<string>("Subtitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Banners");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ImageUrl = "https://example.com/banner1.jpg",
                            IsActive = true,
                            Order = 1,
                            Subtitle = "Prueba el mejor pollo a la brasa",
                            Title = "¡Bienvenido!"
                        },
                        new
                        {
                            Id = 2,
                            ImageUrl = "https://example.com/banner2.jpg",
                            IsActive = true,
                            Order = 2,
                            Subtitle = "2 Pollos x 110 soles",
                            Title = "Oferta del Mes"
                        },
                        new
                        {
                            Id = 3,
                            ImageUrl = "https://example.com/banner3.jpg",
                            IsActive = true,
                            Order = 3,
                            Subtitle = "Solo en zonas seleccionadas",
                            Title = "Delivery Gratis"
                        });
                });

            modelBuilder.Entity("DbModel.Tables.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("DbModel.Tables.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("DocumentNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("DocumentType")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Clients");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Av. Siempre Viva 123",
                            DocumentNumber = "12345678",
                            DocumentType = "DNI",
                            Name = "Juan Perez",
                            Phone = "987654321"
                        },
                        new
                        {
                            Id = 2,
                            Address = "Calle Real 456",
                            DocumentNumber = "87654321",
                            DocumentType = "DNI",
                            Name = "Maria Garcia",
                            Phone = "912345678"
                        },
                        new
                        {
                            Id = 3,
                            Address = "Urb. Los Rosales 789",
                            DocumentNumber = "20123456789",
                            DocumentType = "RUC",
                            Name = "Carlos Sanchez",
                            Phone = "954321098"
                        });
                });

            modelBuilder.Entity("DbModel.Tables.Invoice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CdrUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<string>("PdfUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Serie")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("XmlUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Invoices");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ExternalId = "EXT001",
                            Number = 1,
                            OrderId = 1,
                            Serie = "F001"
                        },
                        new
                        {
                            Id = 2,
                            ExternalId = "EXT002",
                            Number = 2,
                            OrderId = 2,
                            Serie = "F001"
                        },
                        new
                        {
                            Id = 3,
                            ExternalId = "EXT003",
                            Number = 3,
                            OrderId = 3,
                            Serie = "F001"
                        });
                });

            modelBuilder.Entity("DbModel.Tables.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ClientId")
                        .HasColumnType("int");

                    b.Property<int?>("DeliveryUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("PaymentStatus")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("DeliveryUserId");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClientId = 1,
                            DeliveryUserId = 3,
                            OrderDate = new DateTime(2026, 4, 16, 1, 56, 46, 6, DateTimeKind.Utc).AddTicks(563),
                            PaymentStatus = 0,
                            Status = 0,
                            TotalAmount = 65.0m,
                            UserId = 2
                        },
                        new
                        {
                            Id = 2,
                            ClientId = 2,
                            OrderDate = new DateTime(2026, 4, 16, 1, 56, 46, 6, DateTimeKind.Utc).AddTicks(568),
                            PaymentStatus = 0,
                            Status = 0,
                            TotalAmount = 35.0m,
                            UserId = 2
                        },
                        new
                        {
                            Id = 3,
                            ClientId = 3,
                            OrderDate = new DateTime(2026, 4, 16, 1, 56, 46, 6, DateTimeKind.Utc).AddTicks(569),
                            PaymentStatus = 0,
                            Status = 0,
                            TotalAmount = 20.0m,
                            UserId = 1
                        });
                });

            modelBuilder.Entity("DbModel.Tables.OrderDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int?>("SideId")
                        .HasColumnType("int");

                    b.Property<decimal>("Subtotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.HasIndex("SideId");

                    b.ToTable("OrderDetails");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            OrderId = 1,
                            ProductId = 1,
                            Quantity = 1,
                            SideId = 3,
                            Subtotal = 65.0m,
                            UnitPrice = 65.0m
                        },
                        new
                        {
                            Id = 2,
                            OrderId = 2,
                            ProductId = 2,
                            Quantity = 1,
                            SideId = 1,
                            Subtotal = 35.0m,
                            UnitPrice = 35.0m
                        },
                        new
                        {
                            Id = 3,
                            OrderId = 3,
                            ProductId = 3,
                            Quantity = 1,
                            SideId = 2,
                            Subtotal = 20.0m,
                            UnitPrice = 20.0m
                        });
                });

            modelBuilder.Entity("DbModel.Tables.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<string>("PaymentMethod")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TransactionId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Payments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 65.0m,
                            OrderId = 1,
                            PaymentMethod = "Cash",
                            Status = "Paid",
                            TransactionId = "TXN001"
                        },
                        new
                        {
                            Id = 2,
                            Amount = 35.0m,
                            OrderId = 2,
                            PaymentMethod = "Card",
                            Status = "Paid",
                            TransactionId = "TXN002"
                        },
                        new
                        {
                            Id = 3,
                            Amount = 20.0m,
                            OrderId = 3,
                            PaymentMethod = "Yape",
                            Status = "Paid",
                            TransactionId = "TXN003"
                        });
                });

            modelBuilder.Entity("DbModel.Tables.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("BasePrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal?>("SalePrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BasePrice = 65.0m,
                            Description = "Pollo entero con papas y ensalada",
                            ImageUrl = "https://example.com/pollo_entero.jpg",
                            Name = "Pollo a la Brasa (Entero)",
                            SalePrice = 60.0m
                        },
                        new
                        {
                            Id = 2,
                            BasePrice = 35.0m,
                            Description = "Medio pollo con papas y ensalada",
                            ImageUrl = "https://example.com/medio_pollo.jpg",
                            Name = "Medio Pollo"
                        },
                        new
                        {
                            Id = 3,
                            BasePrice = 20.0m,
                            Description = "Un cuarto de pollo con papas y ensalada",
                            ImageUrl = "https://example.com/cuarto_pollo.jpg",
                            Name = "Un Cuarto de Pollo"
                        });
                });

            modelBuilder.Entity("DbModel.Tables.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Waiter"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Delivery"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Client"
                        });
                });

            modelBuilder.Entity("DbModel.Tables.Side", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Sides");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Ensalada Dulce",
                            Price = 5.0m,
                            Type = 0
                        },
                        new
                        {
                            Id = 2,
                            Name = "Ensalada Salada",
                            Price = 5.0m,
                            Type = 1
                        },
                        new
                        {
                            Id = 3,
                            Name = "Papas Fritas",
                            Price = 8.0m,
                            Type = 1
                        });
                });

            modelBuilder.Entity("DbModel.Tables.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("PasswordResetToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("PasswordResetTokenExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<string>("VerificationToken")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "admin@empresa.com",
                            IsVerified = false,
                            Name = "Admin",
                            PasswordHash = "$2a$11$g9p.pmoBRECs8uL3nf0ns.ljh.I/VXgF9Mw/aT6LeVEGfz8oQ/QYG",
                            RoleId = 1
                        },
                        new
                        {
                            Id = 2,
                            Email = "mozo1@example.com",
                            IsVerified = false,
                            Name = "Mozo 1",
                            PasswordHash = "AQAAAAIAAYagAAAAEP0O0O0O0O0O0O0O0O0O0O0O0O0O0O0O0O0O0O0O0O0O0O0O0O0O0O0O0O0O0O0O",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 3,
                            Email = "delivery1@example.com",
                            IsVerified = false,
                            Name = "Delivery 1",
                            PasswordHash = "AQAAAAIAAYagAAAAEP0O0O0O0O0O0O0O0O0O0O0O0O0O0O0O0O0O0O0O0O0O0O0O0O0O0O0O0O0O0O0O",
                            RoleId = 3
                        });
                });

            modelBuilder.Entity("DbModel.Tables.Order", b =>
                {
                    b.HasOne("DbModel.Tables.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId");

                    b.HasOne("DbModel.Tables.User", "DeliveryUser")
                        .WithMany()
                        .HasForeignKey("DeliveryUserId");

                    b.HasOne("DbModel.Tables.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("DeliveryUser");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DbModel.Tables.OrderDetail", b =>
                {
                    b.HasOne("DbModel.Tables.Order", "Order")
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DbModel.Tables.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DbModel.Tables.Side", "Side")
                        .WithMany()
                        .HasForeignKey("SideId");

                    b.Navigation("Order");

                    b.Navigation("Product");

                    b.Navigation("Side");
                });

            modelBuilder.Entity("DbModel.Tables.Product", b =>
                {
                    b.HasOne("DbModel.Tables.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("DbModel.Tables.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("DbModel.Tables.Order", b =>
                {
                    b.Navigation("OrderDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
